version: "3"

services:
  postgres:
      container_name: cah_postgres
      image: postgres:11.1-alpine
      restart: always
      ports: 
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment: 
        POSTGRES_DB: cah_dev
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker

  redis:
    container_name: cah_redis
    image: redis:5.0.3-alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - redis-data:/data
  
volumes: 
  redis-data:
  postgres-data:
