// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// AccountType is an object representing the database table.
type AccountType struct {
	ID           int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Type         null.String `boil:"type" json:"type,omitempty" toml:"type" yaml:"type,omitempty"`
	RequestLimit int         `boil:"request_limit" json:"request_limit" toml:"request_limit" yaml:"request_limit"`
	APIKeyLimit  int         `boil:"api_key_limit" json:"api_key_limit" toml:"api_key_limit" yaml:"api_key_limit"`
	CreatedAt    time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *accountTypeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accountTypeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccountTypeColumns = struct {
	ID           string
	Type         string
	RequestLimit string
	APIKeyLimit  string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	Type:         "type",
	RequestLimit: "request_limit",
	APIKeyLimit:  "api_key_limit",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

// accountTypeR is where relationships are stored.
type accountTypeR struct {
	UserAccountTypeHistories UserAccountTypeHistorySlice
}

// accountTypeL is where Load methods for each relationship are stored.
type accountTypeL struct{}

var (
	accountTypeColumns               = []string{"id", "type", "request_limit", "api_key_limit", "created_at", "updated_at"}
	accountTypeColumnsWithoutDefault = []string{"request_limit", "api_key_limit"}
	accountTypeColumnsWithDefault    = []string{"id", "type", "created_at", "updated_at"}
	accountTypePrimaryKeyColumns     = []string{"id"}
)

type (
	// AccountTypeSlice is an alias for a slice of pointers to AccountType.
	// This should generally be used opposed to []AccountType.
	AccountTypeSlice []*AccountType
	// AccountTypeHook is the signature for custom AccountType hook methods
	AccountTypeHook func(boil.Executor, *AccountType) error

	accountTypeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accountTypeType                 = reflect.TypeOf(&AccountType{})
	accountTypeMapping              = queries.MakeStructMapping(accountTypeType)
	accountTypePrimaryKeyMapping, _ = queries.BindMapping(accountTypeType, accountTypeMapping, accountTypePrimaryKeyColumns)
	accountTypeInsertCacheMut       sync.RWMutex
	accountTypeInsertCache          = make(map[string]insertCache)
	accountTypeUpdateCacheMut       sync.RWMutex
	accountTypeUpdateCache          = make(map[string]updateCache)
	accountTypeUpsertCacheMut       sync.RWMutex
	accountTypeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var accountTypeBeforeInsertHooks []AccountTypeHook
var accountTypeBeforeUpdateHooks []AccountTypeHook
var accountTypeBeforeDeleteHooks []AccountTypeHook
var accountTypeBeforeUpsertHooks []AccountTypeHook

var accountTypeAfterInsertHooks []AccountTypeHook
var accountTypeAfterSelectHooks []AccountTypeHook
var accountTypeAfterUpdateHooks []AccountTypeHook
var accountTypeAfterDeleteHooks []AccountTypeHook
var accountTypeAfterUpsertHooks []AccountTypeHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AccountType) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range accountTypeBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AccountType) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range accountTypeBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AccountType) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range accountTypeBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AccountType) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range accountTypeBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AccountType) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range accountTypeAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AccountType) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range accountTypeAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AccountType) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range accountTypeAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AccountType) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range accountTypeAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AccountType) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range accountTypeAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAccountTypeHook registers your hook function for all future operations.
func AddAccountTypeHook(hookPoint boil.HookPoint, accountTypeHook AccountTypeHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		accountTypeBeforeInsertHooks = append(accountTypeBeforeInsertHooks, accountTypeHook)
	case boil.BeforeUpdateHook:
		accountTypeBeforeUpdateHooks = append(accountTypeBeforeUpdateHooks, accountTypeHook)
	case boil.BeforeDeleteHook:
		accountTypeBeforeDeleteHooks = append(accountTypeBeforeDeleteHooks, accountTypeHook)
	case boil.BeforeUpsertHook:
		accountTypeBeforeUpsertHooks = append(accountTypeBeforeUpsertHooks, accountTypeHook)
	case boil.AfterInsertHook:
		accountTypeAfterInsertHooks = append(accountTypeAfterInsertHooks, accountTypeHook)
	case boil.AfterSelectHook:
		accountTypeAfterSelectHooks = append(accountTypeAfterSelectHooks, accountTypeHook)
	case boil.AfterUpdateHook:
		accountTypeAfterUpdateHooks = append(accountTypeAfterUpdateHooks, accountTypeHook)
	case boil.AfterDeleteHook:
		accountTypeAfterDeleteHooks = append(accountTypeAfterDeleteHooks, accountTypeHook)
	case boil.AfterUpsertHook:
		accountTypeAfterUpsertHooks = append(accountTypeAfterUpsertHooks, accountTypeHook)
	}
}

// OneP returns a single accountType record from the query, and panics on error.
func (q accountTypeQuery) OneP() *AccountType {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single accountType record from the query.
func (q accountTypeQuery) One() (*AccountType, error) {
	o := &AccountType{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for account_types")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all AccountType records from the query, and panics on error.
func (q accountTypeQuery) AllP() AccountTypeSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all AccountType records from the query.
func (q accountTypeQuery) All() (AccountTypeSlice, error) {
	var o []*AccountType

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AccountType slice")
	}

	if len(accountTypeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all AccountType records in the query, and panics on error.
func (q accountTypeQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all AccountType records in the query.
func (q accountTypeQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count account_types rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q accountTypeQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q accountTypeQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if account_types exists")
	}

	return count > 0, nil
}

// UserAccountTypeHistoriesG retrieves all the user_account_type_history's user account type history.
func (o *AccountType) UserAccountTypeHistoriesG(mods ...qm.QueryMod) userAccountTypeHistoryQuery {
	return o.UserAccountTypeHistories(boil.GetDB(), mods...)
}

// UserAccountTypeHistories retrieves all the user_account_type_history's user account type history with an executor.
func (o *AccountType) UserAccountTypeHistories(exec boil.Executor, mods ...qm.QueryMod) userAccountTypeHistoryQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"user_account_type_history\".\"account_type_id\"=?", o.ID),
	)

	query := UserAccountTypeHistories(exec, queryMods...)
	queries.SetFrom(query.Query, "\"user_account_type_history\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"user_account_type_history\".*"})
	}

	return query
}

// LoadUserAccountTypeHistories allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (accountTypeL) LoadUserAccountTypeHistories(e boil.Executor, singular bool, maybeAccountType interface{}) error {
	var slice []*AccountType
	var object *AccountType

	count := 1
	if singular {
		object = maybeAccountType.(*AccountType)
	} else {
		slice = *maybeAccountType.(*[]*AccountType)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &accountTypeR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &accountTypeR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"user_account_type_history\" where \"account_type_id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load user_account_type_history")
	}
	defer results.Close()

	var resultSlice []*UserAccountTypeHistory
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice user_account_type_history")
	}

	if len(userAccountTypeHistoryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.UserAccountTypeHistories = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.AccountTypeID {
				local.R.UserAccountTypeHistories = append(local.R.UserAccountTypeHistories, foreign)
				break
			}
		}
	}

	return nil
}

// AddUserAccountTypeHistoriesG adds the given related objects to the existing relationships
// of the account_type, optionally inserting them as new records.
// Appends related to o.R.UserAccountTypeHistories.
// Sets related.R.AccountType appropriately.
// Uses the global database handle.
func (o *AccountType) AddUserAccountTypeHistoriesG(insert bool, related ...*UserAccountTypeHistory) error {
	return o.AddUserAccountTypeHistories(boil.GetDB(), insert, related...)
}

// AddUserAccountTypeHistoriesP adds the given related objects to the existing relationships
// of the account_type, optionally inserting them as new records.
// Appends related to o.R.UserAccountTypeHistories.
// Sets related.R.AccountType appropriately.
// Panics on error.
func (o *AccountType) AddUserAccountTypeHistoriesP(exec boil.Executor, insert bool, related ...*UserAccountTypeHistory) {
	if err := o.AddUserAccountTypeHistories(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddUserAccountTypeHistoriesGP adds the given related objects to the existing relationships
// of the account_type, optionally inserting them as new records.
// Appends related to o.R.UserAccountTypeHistories.
// Sets related.R.AccountType appropriately.
// Uses the global database handle and panics on error.
func (o *AccountType) AddUserAccountTypeHistoriesGP(insert bool, related ...*UserAccountTypeHistory) {
	if err := o.AddUserAccountTypeHistories(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddUserAccountTypeHistories adds the given related objects to the existing relationships
// of the account_type, optionally inserting them as new records.
// Appends related to o.R.UserAccountTypeHistories.
// Sets related.R.AccountType appropriately.
func (o *AccountType) AddUserAccountTypeHistories(exec boil.Executor, insert bool, related ...*UserAccountTypeHistory) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.AccountTypeID = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"user_account_type_history\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"account_type_id"}),
				strmangle.WhereClause("\"", "\"", 2, userAccountTypeHistoryPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.AccountTypeID = o.ID
		}
	}

	if o.R == nil {
		o.R = &accountTypeR{
			UserAccountTypeHistories: related,
		}
	} else {
		o.R.UserAccountTypeHistories = append(o.R.UserAccountTypeHistories, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &userAccountTypeHistoryR{
				AccountType: o,
			}
		} else {
			rel.R.AccountType = o
		}
	}
	return nil
}

// AccountTypesG retrieves all records.
func AccountTypesG(mods ...qm.QueryMod) accountTypeQuery {
	return AccountTypes(boil.GetDB(), mods...)
}

// AccountTypes retrieves all the records using an executor.
func AccountTypes(exec boil.Executor, mods ...qm.QueryMod) accountTypeQuery {
	mods = append(mods, qm.From("\"account_types\""))
	return accountTypeQuery{NewQuery(exec, mods...)}
}

// FindAccountTypeG retrieves a single record by ID.
func FindAccountTypeG(id int, selectCols ...string) (*AccountType, error) {
	return FindAccountType(boil.GetDB(), id, selectCols...)
}

// FindAccountTypeGP retrieves a single record by ID, and panics on error.
func FindAccountTypeGP(id int, selectCols ...string) *AccountType {
	retobj, err := FindAccountType(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindAccountType retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccountType(exec boil.Executor, id int, selectCols ...string) (*AccountType, error) {
	accountTypeObj := &AccountType{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"account_types\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(accountTypeObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from account_types")
	}

	return accountTypeObj, nil
}

// FindAccountTypeP retrieves a single record by ID with an executor, and panics on error.
func FindAccountTypeP(exec boil.Executor, id int, selectCols ...string) *AccountType {
	retobj, err := FindAccountType(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *AccountType) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *AccountType) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *AccountType) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *AccountType) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no account_types provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountTypeColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	accountTypeInsertCacheMut.RLock()
	cache, cached := accountTypeInsertCache[key]
	accountTypeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			accountTypeColumns,
			accountTypeColumnsWithDefault,
			accountTypeColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(accountTypeType, accountTypeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accountTypeType, accountTypeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"account_types\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"account_types\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into account_types")
	}

	if !cached {
		accountTypeInsertCacheMut.Lock()
		accountTypeInsertCache[key] = cache
		accountTypeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single AccountType record. See Update for
// whitelist behavior description.
func (o *AccountType) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single AccountType record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *AccountType) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the AccountType, and panics on error.
// See Update for whitelist behavior description.
func (o *AccountType) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the AccountType.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *AccountType) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	accountTypeUpdateCacheMut.RLock()
	cache, cached := accountTypeUpdateCache[key]
	accountTypeUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			accountTypeColumns,
			accountTypePrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update account_types, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"account_types\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, accountTypePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accountTypeType, accountTypeMapping, append(wl, accountTypePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update account_types row")
	}

	if !cached {
		accountTypeUpdateCacheMut.Lock()
		accountTypeUpdateCache[key] = cache
		accountTypeUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q accountTypeQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q accountTypeQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for account_types")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o AccountTypeSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o AccountTypeSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o AccountTypeSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccountTypeSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"account_types\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accountTypePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in accountType slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *AccountType) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *AccountType) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *AccountType) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *AccountType) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no account_types provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountTypeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accountTypeUpsertCacheMut.RLock()
	cache, cached := accountTypeUpsertCache[key]
	accountTypeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			accountTypeColumns,
			accountTypeColumnsWithDefault,
			accountTypeColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			accountTypeColumns,
			accountTypePrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert account_types, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(accountTypePrimaryKeyColumns))
			copy(conflict, accountTypePrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"account_types\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(accountTypeType, accountTypeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accountTypeType, accountTypeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert account_types")
	}

	if !cached {
		accountTypeUpsertCacheMut.Lock()
		accountTypeUpsertCache[key] = cache
		accountTypeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single AccountType record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *AccountType) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single AccountType record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *AccountType) DeleteG() error {
	if o == nil {
		return errors.New("models: no AccountType provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single AccountType record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *AccountType) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single AccountType record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccountType) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no AccountType provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accountTypePrimaryKeyMapping)
	sql := "DELETE FROM \"account_types\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from account_types")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q accountTypeQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q accountTypeQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no accountTypeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from account_types")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o AccountTypeSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o AccountTypeSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no AccountType slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o AccountTypeSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccountTypeSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no AccountType slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(accountTypeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"account_types\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountTypePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from accountType slice")
	}

	if len(accountTypeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *AccountType) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *AccountType) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *AccountType) ReloadG() error {
	if o == nil {
		return errors.New("models: no AccountType provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccountType) Reload(exec boil.Executor) error {
	ret, err := FindAccountType(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *AccountTypeSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *AccountTypeSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountTypeSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty AccountTypeSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountTypeSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	accountTypes := AccountTypeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"account_types\".* FROM \"account_types\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountTypePrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&accountTypes)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AccountTypeSlice")
	}

	*o = accountTypes

	return nil
}

// AccountTypeExists checks if the AccountType row exists.
func AccountTypeExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"account_types\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if account_types exists")
	}

	return exists, nil
}

// AccountTypeExistsG checks if the AccountType row exists.
func AccountTypeExistsG(id int) (bool, error) {
	return AccountTypeExists(boil.GetDB(), id)
}

// AccountTypeExistsGP checks if the AccountType row exists. Panics on error.
func AccountTypeExistsGP(id int) bool {
	e, err := AccountTypeExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// AccountTypeExistsP checks if the AccountType row exists. Panics on error.
func AccountTypeExistsP(exec boil.Executor, id int) bool {
	e, err := AccountTypeExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
