// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// BlackCard is an object representing the database table.
type BlackCard struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Text      string    `boil:"text" json:"text" toml:"text" yaml:"text"`
	Pick      int       `boil:"pick" json:"pick" toml:"pick" yaml:"pick"`
	SetID     int       `boil:"set_id" json:"set_id" toml:"set_id" yaml:"set_id"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *blackCardR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L blackCardL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BlackCardColumns = struct {
	ID        string
	Text      string
	Pick      string
	SetID     string
	CreatedAt string
	UpdatedAt string
	DeletedAt string
}{
	ID:        "id",
	Text:      "text",
	Pick:      "pick",
	SetID:     "set_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

// blackCardR is where relationships are stored.
type blackCardR struct {
	Set *Set
}

// blackCardL is where Load methods for each relationship are stored.
type blackCardL struct{}

var (
	blackCardColumns               = []string{"id", "text", "pick", "set_id", "created_at", "updated_at", "deleted_at"}
	blackCardColumnsWithoutDefault = []string{"text", "pick", "set_id", "deleted_at"}
	blackCardColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	blackCardPrimaryKeyColumns     = []string{"id"}
)

type (
	// BlackCardSlice is an alias for a slice of pointers to BlackCard.
	// This should generally be used opposed to []BlackCard.
	BlackCardSlice []*BlackCard
	// BlackCardHook is the signature for custom BlackCard hook methods
	BlackCardHook func(boil.Executor, *BlackCard) error

	blackCardQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	blackCardType                 = reflect.TypeOf(&BlackCard{})
	blackCardMapping              = queries.MakeStructMapping(blackCardType)
	blackCardPrimaryKeyMapping, _ = queries.BindMapping(blackCardType, blackCardMapping, blackCardPrimaryKeyColumns)
	blackCardInsertCacheMut       sync.RWMutex
	blackCardInsertCache          = make(map[string]insertCache)
	blackCardUpdateCacheMut       sync.RWMutex
	blackCardUpdateCache          = make(map[string]updateCache)
	blackCardUpsertCacheMut       sync.RWMutex
	blackCardUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var blackCardBeforeInsertHooks []BlackCardHook
var blackCardBeforeUpdateHooks []BlackCardHook
var blackCardBeforeDeleteHooks []BlackCardHook
var blackCardBeforeUpsertHooks []BlackCardHook

var blackCardAfterInsertHooks []BlackCardHook
var blackCardAfterSelectHooks []BlackCardHook
var blackCardAfterUpdateHooks []BlackCardHook
var blackCardAfterDeleteHooks []BlackCardHook
var blackCardAfterUpsertHooks []BlackCardHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *BlackCard) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range blackCardBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *BlackCard) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range blackCardBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *BlackCard) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range blackCardBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *BlackCard) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range blackCardBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *BlackCard) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range blackCardAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *BlackCard) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range blackCardAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *BlackCard) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range blackCardAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *BlackCard) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range blackCardAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *BlackCard) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range blackCardAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBlackCardHook registers your hook function for all future operations.
func AddBlackCardHook(hookPoint boil.HookPoint, blackCardHook BlackCardHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		blackCardBeforeInsertHooks = append(blackCardBeforeInsertHooks, blackCardHook)
	case boil.BeforeUpdateHook:
		blackCardBeforeUpdateHooks = append(blackCardBeforeUpdateHooks, blackCardHook)
	case boil.BeforeDeleteHook:
		blackCardBeforeDeleteHooks = append(blackCardBeforeDeleteHooks, blackCardHook)
	case boil.BeforeUpsertHook:
		blackCardBeforeUpsertHooks = append(blackCardBeforeUpsertHooks, blackCardHook)
	case boil.AfterInsertHook:
		blackCardAfterInsertHooks = append(blackCardAfterInsertHooks, blackCardHook)
	case boil.AfterSelectHook:
		blackCardAfterSelectHooks = append(blackCardAfterSelectHooks, blackCardHook)
	case boil.AfterUpdateHook:
		blackCardAfterUpdateHooks = append(blackCardAfterUpdateHooks, blackCardHook)
	case boil.AfterDeleteHook:
		blackCardAfterDeleteHooks = append(blackCardAfterDeleteHooks, blackCardHook)
	case boil.AfterUpsertHook:
		blackCardAfterUpsertHooks = append(blackCardAfterUpsertHooks, blackCardHook)
	}
}

// OneP returns a single blackCard record from the query, and panics on error.
func (q blackCardQuery) OneP() *BlackCard {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single blackCard record from the query.
func (q blackCardQuery) One() (*BlackCard, error) {
	o := &BlackCard{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for black_cards")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all BlackCard records from the query, and panics on error.
func (q blackCardQuery) AllP() BlackCardSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all BlackCard records from the query.
func (q blackCardQuery) All() (BlackCardSlice, error) {
	var o []*BlackCard

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to BlackCard slice")
	}

	if len(blackCardAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all BlackCard records in the query, and panics on error.
func (q blackCardQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all BlackCard records in the query.
func (q blackCardQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count black_cards rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q blackCardQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q blackCardQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if black_cards exists")
	}

	return count > 0, nil
}

// SetG pointed to by the foreign key.
func (o *BlackCard) SetG(mods ...qm.QueryMod) setQuery {
	return o.Set(boil.GetDB(), mods...)
}

// Set pointed to by the foreign key.
func (o *BlackCard) Set(exec boil.Executor, mods ...qm.QueryMod) setQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.SetID),
	}

	queryMods = append(queryMods, mods...)

	query := Sets(exec, queryMods...)
	queries.SetFrom(query.Query, "\"sets\"")

	return query
} // LoadSet allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (blackCardL) LoadSet(e boil.Executor, singular bool, maybeBlackCard interface{}) error {
	var slice []*BlackCard
	var object *BlackCard

	count := 1
	if singular {
		object = maybeBlackCard.(*BlackCard)
	} else {
		slice = *maybeBlackCard.(*[]*BlackCard)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &blackCardR{}
		}
		args[0] = object.SetID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &blackCardR{}
			}
			args[i] = obj.SetID
		}
	}

	query := fmt.Sprintf(
		"select * from \"sets\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Set")
	}
	defer results.Close()

	var resultSlice []*Set
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Set")
	}

	if len(blackCardAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Set = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SetID == foreign.ID {
				local.R.Set = foreign
				break
			}
		}
	}

	return nil
}

// SetSetG of the black_card to the related item.
// Sets o.R.Set to related.
// Adds o to related.R.BlackCards.
// Uses the global database handle.
func (o *BlackCard) SetSetG(insert bool, related *Set) error {
	return o.SetSet(boil.GetDB(), insert, related)
}

// SetSetP of the black_card to the related item.
// Sets o.R.Set to related.
// Adds o to related.R.BlackCards.
// Panics on error.
func (o *BlackCard) SetSetP(exec boil.Executor, insert bool, related *Set) {
	if err := o.SetSet(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetSetGP of the black_card to the related item.
// Sets o.R.Set to related.
// Adds o to related.R.BlackCards.
// Uses the global database handle and panics on error.
func (o *BlackCard) SetSetGP(insert bool, related *Set) {
	if err := o.SetSet(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetSet of the black_card to the related item.
// Sets o.R.Set to related.
// Adds o to related.R.BlackCards.
func (o *BlackCard) SetSet(exec boil.Executor, insert bool, related *Set) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"black_cards\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"set_id"}),
		strmangle.WhereClause("\"", "\"", 2, blackCardPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SetID = related.ID

	if o.R == nil {
		o.R = &blackCardR{
			Set: related,
		}
	} else {
		o.R.Set = related
	}

	if related.R == nil {
		related.R = &setR{
			BlackCards: BlackCardSlice{o},
		}
	} else {
		related.R.BlackCards = append(related.R.BlackCards, o)
	}

	return nil
}

// BlackCardsG retrieves all records.
func BlackCardsG(mods ...qm.QueryMod) blackCardQuery {
	return BlackCards(boil.GetDB(), mods...)
}

// BlackCards retrieves all the records using an executor.
func BlackCards(exec boil.Executor, mods ...qm.QueryMod) blackCardQuery {
	mods = append(mods, qm.From("\"black_cards\""))
	return blackCardQuery{NewQuery(exec, mods...)}
}

// FindBlackCardG retrieves a single record by ID.
func FindBlackCardG(id int, selectCols ...string) (*BlackCard, error) {
	return FindBlackCard(boil.GetDB(), id, selectCols...)
}

// FindBlackCardGP retrieves a single record by ID, and panics on error.
func FindBlackCardGP(id int, selectCols ...string) *BlackCard {
	retobj, err := FindBlackCard(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindBlackCard retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBlackCard(exec boil.Executor, id int, selectCols ...string) (*BlackCard, error) {
	blackCardObj := &BlackCard{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"black_cards\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(blackCardObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from black_cards")
	}

	return blackCardObj, nil
}

// FindBlackCardP retrieves a single record by ID with an executor, and panics on error.
func FindBlackCardP(exec boil.Executor, id int, selectCols ...string) *BlackCard {
	retobj, err := FindBlackCard(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *BlackCard) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *BlackCard) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *BlackCard) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *BlackCard) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no black_cards provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	if o.UpdatedAt.Time.IsZero() {
		o.UpdatedAt.Time = currTime
		o.UpdatedAt.Valid = true
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(blackCardColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	blackCardInsertCacheMut.RLock()
	cache, cached := blackCardInsertCache[key]
	blackCardInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			blackCardColumns,
			blackCardColumnsWithDefault,
			blackCardColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(blackCardType, blackCardMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(blackCardType, blackCardMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"black_cards\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"black_cards\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into black_cards")
	}

	if !cached {
		blackCardInsertCacheMut.Lock()
		blackCardInsertCache[key] = cache
		blackCardInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single BlackCard record. See Update for
// whitelist behavior description.
func (o *BlackCard) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single BlackCard record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *BlackCard) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the BlackCard, and panics on error.
// See Update for whitelist behavior description.
func (o *BlackCard) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the BlackCard.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *BlackCard) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	blackCardUpdateCacheMut.RLock()
	cache, cached := blackCardUpdateCache[key]
	blackCardUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			blackCardColumns,
			blackCardPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update black_cards, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"black_cards\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, blackCardPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(blackCardType, blackCardMapping, append(wl, blackCardPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update black_cards row")
	}

	if !cached {
		blackCardUpdateCacheMut.Lock()
		blackCardUpdateCache[key] = cache
		blackCardUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q blackCardQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q blackCardQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for black_cards")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o BlackCardSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o BlackCardSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o BlackCardSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BlackCardSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), blackCardPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"black_cards\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, blackCardPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in blackCard slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *BlackCard) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *BlackCard) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *BlackCard) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *BlackCard) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no black_cards provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(blackCardColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	blackCardUpsertCacheMut.RLock()
	cache, cached := blackCardUpsertCache[key]
	blackCardUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			blackCardColumns,
			blackCardColumnsWithDefault,
			blackCardColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			blackCardColumns,
			blackCardPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert black_cards, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(blackCardPrimaryKeyColumns))
			copy(conflict, blackCardPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"black_cards\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(blackCardType, blackCardMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(blackCardType, blackCardMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert black_cards")
	}

	if !cached {
		blackCardUpsertCacheMut.Lock()
		blackCardUpsertCache[key] = cache
		blackCardUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single BlackCard record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *BlackCard) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single BlackCard record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *BlackCard) DeleteG() error {
	if o == nil {
		return errors.New("models: no BlackCard provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single BlackCard record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *BlackCard) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single BlackCard record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BlackCard) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no BlackCard provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), blackCardPrimaryKeyMapping)
	sql := "DELETE FROM \"black_cards\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from black_cards")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q blackCardQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q blackCardQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no blackCardQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from black_cards")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o BlackCardSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o BlackCardSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no BlackCard slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o BlackCardSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BlackCardSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no BlackCard slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(blackCardBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), blackCardPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"black_cards\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, blackCardPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from blackCard slice")
	}

	if len(blackCardAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *BlackCard) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *BlackCard) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *BlackCard) ReloadG() error {
	if o == nil {
		return errors.New("models: no BlackCard provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BlackCard) Reload(exec boil.Executor) error {
	ret, err := FindBlackCard(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *BlackCardSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *BlackCardSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BlackCardSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty BlackCardSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BlackCardSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	blackCards := BlackCardSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), blackCardPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"black_cards\".* FROM \"black_cards\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, blackCardPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&blackCards)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BlackCardSlice")
	}

	*o = blackCards

	return nil
}

// BlackCardExists checks if the BlackCard row exists.
func BlackCardExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"black_cards\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if black_cards exists")
	}

	return exists, nil
}

// BlackCardExistsG checks if the BlackCard row exists.
func BlackCardExistsG(id int) (bool, error) {
	return BlackCardExists(boil.GetDB(), id)
}

// BlackCardExistsGP checks if the BlackCard row exists. Panics on error.
func BlackCardExistsGP(id int) bool {
	e, err := BlackCardExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// BlackCardExistsP checks if the BlackCard row exists. Panics on error.
func BlackCardExistsP(exec boil.Executor, id int) bool {
	e, err := BlackCardExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
