// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccountTypes           string
	APIKeys                string
	BlackCards             string
	GooseDBVersion         string
	Sets                   string
	UserAccountTypeHistory string
	UserAPIKeys            string
	UserVerificationTokens string
	Users                  string
	WhiteCards             string
}{
	AccountTypes:   "account_types",
	APIKeys:        "api_keys",
	BlackCards:     "black_cards",
	GooseDBVersion: "goose_db_version",
	Sets:           "sets",
	UserAccountTypeHistory: "user_account_type_history",
	UserAPIKeys:            "user_api_keys",
	UserVerificationTokens: "user_verification_tokens",
	Users:      "users",
	WhiteCards: "white_cards",
}
