// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// UserAPIKey is an object representing the database table.
type UserAPIKey struct {
	ID       int `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID   int `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	APIKeyID int `boil:"api_key_id" json:"api_key_id" toml:"api_key_id" yaml:"api_key_id"`

	R *userAPIKeyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userAPIKeyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserAPIKeyColumns = struct {
	ID       string
	UserID   string
	APIKeyID string
}{
	ID:       "id",
	UserID:   "user_id",
	APIKeyID: "api_key_id",
}

// userAPIKeyR is where relationships are stored.
type userAPIKeyR struct {
	User   *User
	APIKey *APIKey
}

// userAPIKeyL is where Load methods for each relationship are stored.
type userAPIKeyL struct{}

var (
	userAPIKeyColumns               = []string{"id", "user_id", "api_key_id"}
	userAPIKeyColumnsWithoutDefault = []string{"user_id", "api_key_id"}
	userAPIKeyColumnsWithDefault    = []string{"id"}
	userAPIKeyPrimaryKeyColumns     = []string{"id"}
)

type (
	// UserAPIKeySlice is an alias for a slice of pointers to UserAPIKey.
	// This should generally be used opposed to []UserAPIKey.
	UserAPIKeySlice []*UserAPIKey
	// UserAPIKeyHook is the signature for custom UserAPIKey hook methods
	UserAPIKeyHook func(boil.Executor, *UserAPIKey) error

	userAPIKeyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userAPIKeyType                 = reflect.TypeOf(&UserAPIKey{})
	userAPIKeyMapping              = queries.MakeStructMapping(userAPIKeyType)
	userAPIKeyPrimaryKeyMapping, _ = queries.BindMapping(userAPIKeyType, userAPIKeyMapping, userAPIKeyPrimaryKeyColumns)
	userAPIKeyInsertCacheMut       sync.RWMutex
	userAPIKeyInsertCache          = make(map[string]insertCache)
	userAPIKeyUpdateCacheMut       sync.RWMutex
	userAPIKeyUpdateCache          = make(map[string]updateCache)
	userAPIKeyUpsertCacheMut       sync.RWMutex
	userAPIKeyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var userAPIKeyBeforeInsertHooks []UserAPIKeyHook
var userAPIKeyBeforeUpdateHooks []UserAPIKeyHook
var userAPIKeyBeforeDeleteHooks []UserAPIKeyHook
var userAPIKeyBeforeUpsertHooks []UserAPIKeyHook

var userAPIKeyAfterInsertHooks []UserAPIKeyHook
var userAPIKeyAfterSelectHooks []UserAPIKeyHook
var userAPIKeyAfterUpdateHooks []UserAPIKeyHook
var userAPIKeyAfterDeleteHooks []UserAPIKeyHook
var userAPIKeyAfterUpsertHooks []UserAPIKeyHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserAPIKey) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range userAPIKeyBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserAPIKey) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range userAPIKeyBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserAPIKey) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range userAPIKeyBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserAPIKey) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range userAPIKeyBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserAPIKey) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range userAPIKeyAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserAPIKey) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range userAPIKeyAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserAPIKey) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range userAPIKeyAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserAPIKey) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range userAPIKeyAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserAPIKey) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range userAPIKeyAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserAPIKeyHook registers your hook function for all future operations.
func AddUserAPIKeyHook(hookPoint boil.HookPoint, userAPIKeyHook UserAPIKeyHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		userAPIKeyBeforeInsertHooks = append(userAPIKeyBeforeInsertHooks, userAPIKeyHook)
	case boil.BeforeUpdateHook:
		userAPIKeyBeforeUpdateHooks = append(userAPIKeyBeforeUpdateHooks, userAPIKeyHook)
	case boil.BeforeDeleteHook:
		userAPIKeyBeforeDeleteHooks = append(userAPIKeyBeforeDeleteHooks, userAPIKeyHook)
	case boil.BeforeUpsertHook:
		userAPIKeyBeforeUpsertHooks = append(userAPIKeyBeforeUpsertHooks, userAPIKeyHook)
	case boil.AfterInsertHook:
		userAPIKeyAfterInsertHooks = append(userAPIKeyAfterInsertHooks, userAPIKeyHook)
	case boil.AfterSelectHook:
		userAPIKeyAfterSelectHooks = append(userAPIKeyAfterSelectHooks, userAPIKeyHook)
	case boil.AfterUpdateHook:
		userAPIKeyAfterUpdateHooks = append(userAPIKeyAfterUpdateHooks, userAPIKeyHook)
	case boil.AfterDeleteHook:
		userAPIKeyAfterDeleteHooks = append(userAPIKeyAfterDeleteHooks, userAPIKeyHook)
	case boil.AfterUpsertHook:
		userAPIKeyAfterUpsertHooks = append(userAPIKeyAfterUpsertHooks, userAPIKeyHook)
	}
}

// OneP returns a single userAPIKey record from the query, and panics on error.
func (q userAPIKeyQuery) OneP() *UserAPIKey {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single userAPIKey record from the query.
func (q userAPIKeyQuery) One() (*UserAPIKey, error) {
	o := &UserAPIKey{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for user_api_keys")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all UserAPIKey records from the query, and panics on error.
func (q userAPIKeyQuery) AllP() UserAPIKeySlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all UserAPIKey records from the query.
func (q userAPIKeyQuery) All() (UserAPIKeySlice, error) {
	var o []*UserAPIKey

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserAPIKey slice")
	}

	if len(userAPIKeyAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all UserAPIKey records in the query, and panics on error.
func (q userAPIKeyQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all UserAPIKey records in the query.
func (q userAPIKeyQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count user_api_keys rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q userAPIKeyQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q userAPIKeyQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if user_api_keys exists")
	}

	return count > 0, nil
}

// UserG pointed to by the foreign key.
func (o *UserAPIKey) UserG(mods ...qm.QueryMod) userQuery {
	return o.User(boil.GetDB(), mods...)
}

// User pointed to by the foreign key.
func (o *UserAPIKey) User(exec boil.Executor, mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(exec, queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// APIKeyG pointed to by the foreign key.
func (o *UserAPIKey) APIKeyG(mods ...qm.QueryMod) apiKeyQuery {
	return o.APIKey(boil.GetDB(), mods...)
}

// APIKey pointed to by the foreign key.
func (o *UserAPIKey) APIKey(exec boil.Executor, mods ...qm.QueryMod) apiKeyQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.APIKeyID),
	}

	queryMods = append(queryMods, mods...)

	query := APIKeys(exec, queryMods...)
	queries.SetFrom(query.Query, "\"api_keys\"")

	return query
} // LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (userAPIKeyL) LoadUser(e boil.Executor, singular bool, maybeUserAPIKey interface{}) error {
	var slice []*UserAPIKey
	var object *UserAPIKey

	count := 1
	if singular {
		object = maybeUserAPIKey.(*UserAPIKey)
	} else {
		slice = *maybeUserAPIKey.(*[]*UserAPIKey)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &userAPIKeyR{}
		}
		args[0] = object.UserID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &userAPIKeyR{}
			}
			args[i] = obj.UserID
		}
	}

	query := fmt.Sprintf(
		"select * from \"users\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}
	defer results.Close()

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if len(userAPIKeyAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.User = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				break
			}
		}
	}

	return nil
}

// LoadAPIKey allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (userAPIKeyL) LoadAPIKey(e boil.Executor, singular bool, maybeUserAPIKey interface{}) error {
	var slice []*UserAPIKey
	var object *UserAPIKey

	count := 1
	if singular {
		object = maybeUserAPIKey.(*UserAPIKey)
	} else {
		slice = *maybeUserAPIKey.(*[]*UserAPIKey)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &userAPIKeyR{}
		}
		args[0] = object.APIKeyID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &userAPIKeyR{}
			}
			args[i] = obj.APIKeyID
		}
	}

	query := fmt.Sprintf(
		"select * from \"api_keys\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load APIKey")
	}
	defer results.Close()

	var resultSlice []*APIKey
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice APIKey")
	}

	if len(userAPIKeyAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.APIKey = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.APIKeyID == foreign.ID {
				local.R.APIKey = foreign
				break
			}
		}
	}

	return nil
}

// SetUserG of the user_api_key to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserAPIKeys.
// Uses the global database handle.
func (o *UserAPIKey) SetUserG(insert bool, related *User) error {
	return o.SetUser(boil.GetDB(), insert, related)
}

// SetUserP of the user_api_key to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserAPIKeys.
// Panics on error.
func (o *UserAPIKey) SetUserP(exec boil.Executor, insert bool, related *User) {
	if err := o.SetUser(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUserGP of the user_api_key to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserAPIKeys.
// Uses the global database handle and panics on error.
func (o *UserAPIKey) SetUserGP(insert bool, related *User) {
	if err := o.SetUser(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUser of the user_api_key to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserAPIKeys.
func (o *UserAPIKey) SetUser(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_api_keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userAPIKeyPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID

	if o.R == nil {
		o.R = &userAPIKeyR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserAPIKeys: UserAPIKeySlice{o},
		}
	} else {
		related.R.UserAPIKeys = append(related.R.UserAPIKeys, o)
	}

	return nil
}

// SetAPIKeyG of the user_api_key to the related item.
// Sets o.R.APIKey to related.
// Adds o to related.R.UserAPIKeys.
// Uses the global database handle.
func (o *UserAPIKey) SetAPIKeyG(insert bool, related *APIKey) error {
	return o.SetAPIKey(boil.GetDB(), insert, related)
}

// SetAPIKeyP of the user_api_key to the related item.
// Sets o.R.APIKey to related.
// Adds o to related.R.UserAPIKeys.
// Panics on error.
func (o *UserAPIKey) SetAPIKeyP(exec boil.Executor, insert bool, related *APIKey) {
	if err := o.SetAPIKey(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetAPIKeyGP of the user_api_key to the related item.
// Sets o.R.APIKey to related.
// Adds o to related.R.UserAPIKeys.
// Uses the global database handle and panics on error.
func (o *UserAPIKey) SetAPIKeyGP(insert bool, related *APIKey) {
	if err := o.SetAPIKey(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetAPIKey of the user_api_key to the related item.
// Sets o.R.APIKey to related.
// Adds o to related.R.UserAPIKeys.
func (o *UserAPIKey) SetAPIKey(exec boil.Executor, insert bool, related *APIKey) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_api_keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"api_key_id"}),
		strmangle.WhereClause("\"", "\"", 2, userAPIKeyPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.APIKeyID = related.ID

	if o.R == nil {
		o.R = &userAPIKeyR{
			APIKey: related,
		}
	} else {
		o.R.APIKey = related
	}

	if related.R == nil {
		related.R = &apiKeyR{
			UserAPIKeys: UserAPIKeySlice{o},
		}
	} else {
		related.R.UserAPIKeys = append(related.R.UserAPIKeys, o)
	}

	return nil
}

// UserAPIKeysG retrieves all records.
func UserAPIKeysG(mods ...qm.QueryMod) userAPIKeyQuery {
	return UserAPIKeys(boil.GetDB(), mods...)
}

// UserAPIKeys retrieves all the records using an executor.
func UserAPIKeys(exec boil.Executor, mods ...qm.QueryMod) userAPIKeyQuery {
	mods = append(mods, qm.From("\"user_api_keys\""))
	return userAPIKeyQuery{NewQuery(exec, mods...)}
}

// FindUserAPIKeyG retrieves a single record by ID.
func FindUserAPIKeyG(id int, selectCols ...string) (*UserAPIKey, error) {
	return FindUserAPIKey(boil.GetDB(), id, selectCols...)
}

// FindUserAPIKeyGP retrieves a single record by ID, and panics on error.
func FindUserAPIKeyGP(id int, selectCols ...string) *UserAPIKey {
	retobj, err := FindUserAPIKey(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindUserAPIKey retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserAPIKey(exec boil.Executor, id int, selectCols ...string) (*UserAPIKey, error) {
	userAPIKeyObj := &UserAPIKey{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_api_keys\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(userAPIKeyObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from user_api_keys")
	}

	return userAPIKeyObj, nil
}

// FindUserAPIKeyP retrieves a single record by ID with an executor, and panics on error.
func FindUserAPIKeyP(exec boil.Executor, id int, selectCols ...string) *UserAPIKey {
	retobj, err := FindUserAPIKey(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *UserAPIKey) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *UserAPIKey) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *UserAPIKey) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *UserAPIKey) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no user_api_keys provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userAPIKeyColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	userAPIKeyInsertCacheMut.RLock()
	cache, cached := userAPIKeyInsertCache[key]
	userAPIKeyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			userAPIKeyColumns,
			userAPIKeyColumnsWithDefault,
			userAPIKeyColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(userAPIKeyType, userAPIKeyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userAPIKeyType, userAPIKeyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_api_keys\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_api_keys\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into user_api_keys")
	}

	if !cached {
		userAPIKeyInsertCacheMut.Lock()
		userAPIKeyInsertCache[key] = cache
		userAPIKeyInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single UserAPIKey record. See Update for
// whitelist behavior description.
func (o *UserAPIKey) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single UserAPIKey record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *UserAPIKey) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the UserAPIKey, and panics on error.
// See Update for whitelist behavior description.
func (o *UserAPIKey) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the UserAPIKey.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *UserAPIKey) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	userAPIKeyUpdateCacheMut.RLock()
	cache, cached := userAPIKeyUpdateCache[key]
	userAPIKeyUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			userAPIKeyColumns,
			userAPIKeyPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update user_api_keys, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_api_keys\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userAPIKeyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userAPIKeyType, userAPIKeyMapping, append(wl, userAPIKeyPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update user_api_keys row")
	}

	if !cached {
		userAPIKeyUpdateCacheMut.Lock()
		userAPIKeyUpdateCache[key] = cache
		userAPIKeyUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q userAPIKeyQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q userAPIKeyQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for user_api_keys")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o UserAPIKeySlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o UserAPIKeySlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o UserAPIKeySlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserAPIKeySlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userAPIKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_api_keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userAPIKeyPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in userAPIKey slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *UserAPIKey) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *UserAPIKey) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *UserAPIKey) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *UserAPIKey) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no user_api_keys provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userAPIKeyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userAPIKeyUpsertCacheMut.RLock()
	cache, cached := userAPIKeyUpsertCache[key]
	userAPIKeyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			userAPIKeyColumns,
			userAPIKeyColumnsWithDefault,
			userAPIKeyColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			userAPIKeyColumns,
			userAPIKeyPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert user_api_keys, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(userAPIKeyPrimaryKeyColumns))
			copy(conflict, userAPIKeyPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"user_api_keys\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(userAPIKeyType, userAPIKeyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userAPIKeyType, userAPIKeyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert user_api_keys")
	}

	if !cached {
		userAPIKeyUpsertCacheMut.Lock()
		userAPIKeyUpsertCache[key] = cache
		userAPIKeyUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single UserAPIKey record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *UserAPIKey) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single UserAPIKey record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *UserAPIKey) DeleteG() error {
	if o == nil {
		return errors.New("models: no UserAPIKey provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single UserAPIKey record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *UserAPIKey) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single UserAPIKey record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserAPIKey) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no UserAPIKey provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userAPIKeyPrimaryKeyMapping)
	sql := "DELETE FROM \"user_api_keys\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from user_api_keys")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q userAPIKeyQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q userAPIKeyQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no userAPIKeyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from user_api_keys")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o UserAPIKeySlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o UserAPIKeySlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no UserAPIKey slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o UserAPIKeySlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserAPIKeySlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no UserAPIKey slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(userAPIKeyBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userAPIKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_api_keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userAPIKeyPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from userAPIKey slice")
	}

	if len(userAPIKeyAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *UserAPIKey) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *UserAPIKey) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *UserAPIKey) ReloadG() error {
	if o == nil {
		return errors.New("models: no UserAPIKey provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserAPIKey) Reload(exec boil.Executor) error {
	ret, err := FindUserAPIKey(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *UserAPIKeySlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *UserAPIKeySlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserAPIKeySlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty UserAPIKeySlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserAPIKeySlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	userAPIKeys := UserAPIKeySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userAPIKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_api_keys\".* FROM \"user_api_keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userAPIKeyPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&userAPIKeys)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserAPIKeySlice")
	}

	*o = userAPIKeys

	return nil
}

// UserAPIKeyExists checks if the UserAPIKey row exists.
func UserAPIKeyExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_api_keys\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if user_api_keys exists")
	}

	return exists, nil
}

// UserAPIKeyExistsG checks if the UserAPIKey row exists.
func UserAPIKeyExistsG(id int) (bool, error) {
	return UserAPIKeyExists(boil.GetDB(), id)
}

// UserAPIKeyExistsGP checks if the UserAPIKey row exists. Panics on error.
func UserAPIKeyExistsGP(id int) bool {
	e, err := UserAPIKeyExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// UserAPIKeyExistsP checks if the UserAPIKey row exists. Panics on error.
func UserAPIKeyExistsP(exec boil.Executor, id int) bool {
	e, err := UserAPIKeyExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
