// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// UserVerificationToken is an object representing the database table.
type UserVerificationToken struct {
	ID         int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID     int       `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Token      string    `boil:"token" json:"token" toml:"token" yaml:"token"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	VerifiedAt null.Time `boil:"verified_at" json:"verified_at,omitempty" toml:"verified_at" yaml:"verified_at,omitempty"`
	ExpiresAt  time.Time `boil:"expires_at" json:"expires_at" toml:"expires_at" yaml:"expires_at"`

	R *userVerificationTokenR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userVerificationTokenL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserVerificationTokenColumns = struct {
	ID         string
	UserID     string
	Token      string
	CreatedAt  string
	VerifiedAt string
	ExpiresAt  string
}{
	ID:         "id",
	UserID:     "user_id",
	Token:      "token",
	CreatedAt:  "created_at",
	VerifiedAt: "verified_at",
	ExpiresAt:  "expires_at",
}

// userVerificationTokenR is where relationships are stored.
type userVerificationTokenR struct {
	User *User
}

// userVerificationTokenL is where Load methods for each relationship are stored.
type userVerificationTokenL struct{}

var (
	userVerificationTokenColumns               = []string{"id", "user_id", "token", "created_at", "verified_at", "expires_at"}
	userVerificationTokenColumnsWithoutDefault = []string{"user_id", "token", "verified_at", "expires_at"}
	userVerificationTokenColumnsWithDefault    = []string{"id", "created_at"}
	userVerificationTokenPrimaryKeyColumns     = []string{"id"}
)

type (
	// UserVerificationTokenSlice is an alias for a slice of pointers to UserVerificationToken.
	// This should generally be used opposed to []UserVerificationToken.
	UserVerificationTokenSlice []*UserVerificationToken
	// UserVerificationTokenHook is the signature for custom UserVerificationToken hook methods
	UserVerificationTokenHook func(boil.Executor, *UserVerificationToken) error

	userVerificationTokenQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userVerificationTokenType                 = reflect.TypeOf(&UserVerificationToken{})
	userVerificationTokenMapping              = queries.MakeStructMapping(userVerificationTokenType)
	userVerificationTokenPrimaryKeyMapping, _ = queries.BindMapping(userVerificationTokenType, userVerificationTokenMapping, userVerificationTokenPrimaryKeyColumns)
	userVerificationTokenInsertCacheMut       sync.RWMutex
	userVerificationTokenInsertCache          = make(map[string]insertCache)
	userVerificationTokenUpdateCacheMut       sync.RWMutex
	userVerificationTokenUpdateCache          = make(map[string]updateCache)
	userVerificationTokenUpsertCacheMut       sync.RWMutex
	userVerificationTokenUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var userVerificationTokenBeforeInsertHooks []UserVerificationTokenHook
var userVerificationTokenBeforeUpdateHooks []UserVerificationTokenHook
var userVerificationTokenBeforeDeleteHooks []UserVerificationTokenHook
var userVerificationTokenBeforeUpsertHooks []UserVerificationTokenHook

var userVerificationTokenAfterInsertHooks []UserVerificationTokenHook
var userVerificationTokenAfterSelectHooks []UserVerificationTokenHook
var userVerificationTokenAfterUpdateHooks []UserVerificationTokenHook
var userVerificationTokenAfterDeleteHooks []UserVerificationTokenHook
var userVerificationTokenAfterUpsertHooks []UserVerificationTokenHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserVerificationToken) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range userVerificationTokenBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserVerificationToken) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range userVerificationTokenBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserVerificationToken) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range userVerificationTokenBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserVerificationToken) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range userVerificationTokenBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserVerificationToken) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range userVerificationTokenAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserVerificationToken) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range userVerificationTokenAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserVerificationToken) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range userVerificationTokenAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserVerificationToken) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range userVerificationTokenAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserVerificationToken) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range userVerificationTokenAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserVerificationTokenHook registers your hook function for all future operations.
func AddUserVerificationTokenHook(hookPoint boil.HookPoint, userVerificationTokenHook UserVerificationTokenHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		userVerificationTokenBeforeInsertHooks = append(userVerificationTokenBeforeInsertHooks, userVerificationTokenHook)
	case boil.BeforeUpdateHook:
		userVerificationTokenBeforeUpdateHooks = append(userVerificationTokenBeforeUpdateHooks, userVerificationTokenHook)
	case boil.BeforeDeleteHook:
		userVerificationTokenBeforeDeleteHooks = append(userVerificationTokenBeforeDeleteHooks, userVerificationTokenHook)
	case boil.BeforeUpsertHook:
		userVerificationTokenBeforeUpsertHooks = append(userVerificationTokenBeforeUpsertHooks, userVerificationTokenHook)
	case boil.AfterInsertHook:
		userVerificationTokenAfterInsertHooks = append(userVerificationTokenAfterInsertHooks, userVerificationTokenHook)
	case boil.AfterSelectHook:
		userVerificationTokenAfterSelectHooks = append(userVerificationTokenAfterSelectHooks, userVerificationTokenHook)
	case boil.AfterUpdateHook:
		userVerificationTokenAfterUpdateHooks = append(userVerificationTokenAfterUpdateHooks, userVerificationTokenHook)
	case boil.AfterDeleteHook:
		userVerificationTokenAfterDeleteHooks = append(userVerificationTokenAfterDeleteHooks, userVerificationTokenHook)
	case boil.AfterUpsertHook:
		userVerificationTokenAfterUpsertHooks = append(userVerificationTokenAfterUpsertHooks, userVerificationTokenHook)
	}
}

// OneP returns a single userVerificationToken record from the query, and panics on error.
func (q userVerificationTokenQuery) OneP() *UserVerificationToken {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single userVerificationToken record from the query.
func (q userVerificationTokenQuery) One() (*UserVerificationToken, error) {
	o := &UserVerificationToken{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for user_verification_tokens")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all UserVerificationToken records from the query, and panics on error.
func (q userVerificationTokenQuery) AllP() UserVerificationTokenSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all UserVerificationToken records from the query.
func (q userVerificationTokenQuery) All() (UserVerificationTokenSlice, error) {
	var o []*UserVerificationToken

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserVerificationToken slice")
	}

	if len(userVerificationTokenAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all UserVerificationToken records in the query, and panics on error.
func (q userVerificationTokenQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all UserVerificationToken records in the query.
func (q userVerificationTokenQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count user_verification_tokens rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q userVerificationTokenQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q userVerificationTokenQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if user_verification_tokens exists")
	}

	return count > 0, nil
}

// UserG pointed to by the foreign key.
func (o *UserVerificationToken) UserG(mods ...qm.QueryMod) userQuery {
	return o.User(boil.GetDB(), mods...)
}

// User pointed to by the foreign key.
func (o *UserVerificationToken) User(exec boil.Executor, mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(exec, queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
} // LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (userVerificationTokenL) LoadUser(e boil.Executor, singular bool, maybeUserVerificationToken interface{}) error {
	var slice []*UserVerificationToken
	var object *UserVerificationToken

	count := 1
	if singular {
		object = maybeUserVerificationToken.(*UserVerificationToken)
	} else {
		slice = *maybeUserVerificationToken.(*[]*UserVerificationToken)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &userVerificationTokenR{}
		}
		args[0] = object.UserID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &userVerificationTokenR{}
			}
			args[i] = obj.UserID
		}
	}

	query := fmt.Sprintf(
		"select * from \"users\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}
	defer results.Close()

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if len(userVerificationTokenAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.User = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				break
			}
		}
	}

	return nil
}

// SetUserG of the user_verification_token to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserVerificationTokens.
// Uses the global database handle.
func (o *UserVerificationToken) SetUserG(insert bool, related *User) error {
	return o.SetUser(boil.GetDB(), insert, related)
}

// SetUserP of the user_verification_token to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserVerificationTokens.
// Panics on error.
func (o *UserVerificationToken) SetUserP(exec boil.Executor, insert bool, related *User) {
	if err := o.SetUser(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUserGP of the user_verification_token to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserVerificationTokens.
// Uses the global database handle and panics on error.
func (o *UserVerificationToken) SetUserGP(insert bool, related *User) {
	if err := o.SetUser(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUser of the user_verification_token to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserVerificationTokens.
func (o *UserVerificationToken) SetUser(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_verification_tokens\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userVerificationTokenPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID

	if o.R == nil {
		o.R = &userVerificationTokenR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserVerificationTokens: UserVerificationTokenSlice{o},
		}
	} else {
		related.R.UserVerificationTokens = append(related.R.UserVerificationTokens, o)
	}

	return nil
}

// UserVerificationTokensG retrieves all records.
func UserVerificationTokensG(mods ...qm.QueryMod) userVerificationTokenQuery {
	return UserVerificationTokens(boil.GetDB(), mods...)
}

// UserVerificationTokens retrieves all the records using an executor.
func UserVerificationTokens(exec boil.Executor, mods ...qm.QueryMod) userVerificationTokenQuery {
	mods = append(mods, qm.From("\"user_verification_tokens\""))
	return userVerificationTokenQuery{NewQuery(exec, mods...)}
}

// FindUserVerificationTokenG retrieves a single record by ID.
func FindUserVerificationTokenG(id int, selectCols ...string) (*UserVerificationToken, error) {
	return FindUserVerificationToken(boil.GetDB(), id, selectCols...)
}

// FindUserVerificationTokenGP retrieves a single record by ID, and panics on error.
func FindUserVerificationTokenGP(id int, selectCols ...string) *UserVerificationToken {
	retobj, err := FindUserVerificationToken(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindUserVerificationToken retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserVerificationToken(exec boil.Executor, id int, selectCols ...string) (*UserVerificationToken, error) {
	userVerificationTokenObj := &UserVerificationToken{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_verification_tokens\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(userVerificationTokenObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from user_verification_tokens")
	}

	return userVerificationTokenObj, nil
}

// FindUserVerificationTokenP retrieves a single record by ID with an executor, and panics on error.
func FindUserVerificationTokenP(exec boil.Executor, id int, selectCols ...string) *UserVerificationToken {
	retobj, err := FindUserVerificationToken(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *UserVerificationToken) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *UserVerificationToken) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *UserVerificationToken) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *UserVerificationToken) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no user_verification_tokens provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userVerificationTokenColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	userVerificationTokenInsertCacheMut.RLock()
	cache, cached := userVerificationTokenInsertCache[key]
	userVerificationTokenInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			userVerificationTokenColumns,
			userVerificationTokenColumnsWithDefault,
			userVerificationTokenColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(userVerificationTokenType, userVerificationTokenMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userVerificationTokenType, userVerificationTokenMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_verification_tokens\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_verification_tokens\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into user_verification_tokens")
	}

	if !cached {
		userVerificationTokenInsertCacheMut.Lock()
		userVerificationTokenInsertCache[key] = cache
		userVerificationTokenInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single UserVerificationToken record. See Update for
// whitelist behavior description.
func (o *UserVerificationToken) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single UserVerificationToken record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *UserVerificationToken) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the UserVerificationToken, and panics on error.
// See Update for whitelist behavior description.
func (o *UserVerificationToken) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the UserVerificationToken.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *UserVerificationToken) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	userVerificationTokenUpdateCacheMut.RLock()
	cache, cached := userVerificationTokenUpdateCache[key]
	userVerificationTokenUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			userVerificationTokenColumns,
			userVerificationTokenPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update user_verification_tokens, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_verification_tokens\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userVerificationTokenPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userVerificationTokenType, userVerificationTokenMapping, append(wl, userVerificationTokenPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update user_verification_tokens row")
	}

	if !cached {
		userVerificationTokenUpdateCacheMut.Lock()
		userVerificationTokenUpdateCache[key] = cache
		userVerificationTokenUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q userVerificationTokenQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q userVerificationTokenQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for user_verification_tokens")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o UserVerificationTokenSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o UserVerificationTokenSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o UserVerificationTokenSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserVerificationTokenSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userVerificationTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_verification_tokens\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userVerificationTokenPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in userVerificationToken slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *UserVerificationToken) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *UserVerificationToken) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *UserVerificationToken) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *UserVerificationToken) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no user_verification_tokens provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userVerificationTokenColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userVerificationTokenUpsertCacheMut.RLock()
	cache, cached := userVerificationTokenUpsertCache[key]
	userVerificationTokenUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			userVerificationTokenColumns,
			userVerificationTokenColumnsWithDefault,
			userVerificationTokenColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			userVerificationTokenColumns,
			userVerificationTokenPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert user_verification_tokens, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(userVerificationTokenPrimaryKeyColumns))
			copy(conflict, userVerificationTokenPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"user_verification_tokens\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(userVerificationTokenType, userVerificationTokenMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userVerificationTokenType, userVerificationTokenMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert user_verification_tokens")
	}

	if !cached {
		userVerificationTokenUpsertCacheMut.Lock()
		userVerificationTokenUpsertCache[key] = cache
		userVerificationTokenUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single UserVerificationToken record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *UserVerificationToken) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single UserVerificationToken record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *UserVerificationToken) DeleteG() error {
	if o == nil {
		return errors.New("models: no UserVerificationToken provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single UserVerificationToken record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *UserVerificationToken) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single UserVerificationToken record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserVerificationToken) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no UserVerificationToken provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userVerificationTokenPrimaryKeyMapping)
	sql := "DELETE FROM \"user_verification_tokens\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from user_verification_tokens")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q userVerificationTokenQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q userVerificationTokenQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no userVerificationTokenQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from user_verification_tokens")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o UserVerificationTokenSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o UserVerificationTokenSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no UserVerificationToken slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o UserVerificationTokenSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserVerificationTokenSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no UserVerificationToken slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(userVerificationTokenBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userVerificationTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_verification_tokens\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userVerificationTokenPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from userVerificationToken slice")
	}

	if len(userVerificationTokenAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *UserVerificationToken) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *UserVerificationToken) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *UserVerificationToken) ReloadG() error {
	if o == nil {
		return errors.New("models: no UserVerificationToken provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserVerificationToken) Reload(exec boil.Executor) error {
	ret, err := FindUserVerificationToken(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *UserVerificationTokenSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *UserVerificationTokenSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserVerificationTokenSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty UserVerificationTokenSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserVerificationTokenSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	userVerificationTokens := UserVerificationTokenSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userVerificationTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_verification_tokens\".* FROM \"user_verification_tokens\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userVerificationTokenPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&userVerificationTokens)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserVerificationTokenSlice")
	}

	*o = userVerificationTokens

	return nil
}

// UserVerificationTokenExists checks if the UserVerificationToken row exists.
func UserVerificationTokenExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_verification_tokens\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if user_verification_tokens exists")
	}

	return exists, nil
}

// UserVerificationTokenExistsG checks if the UserVerificationToken row exists.
func UserVerificationTokenExistsG(id int) (bool, error) {
	return UserVerificationTokenExists(boil.GetDB(), id)
}

// UserVerificationTokenExistsGP checks if the UserVerificationToken row exists. Panics on error.
func UserVerificationTokenExistsGP(id int) bool {
	e, err := UserVerificationTokenExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// UserVerificationTokenExistsP checks if the UserVerificationToken row exists. Panics on error.
func UserVerificationTokenExistsP(exec boil.Executor, id int) bool {
	e, err := UserVerificationTokenExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
